# Generated by Django 5.1.2 on 2024-10-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='useername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
