# Generated by Django 5.1.2 on 2024-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='No answer provided'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='No question provided'),
        ),
    ]
