# Generated by Django 5.1.2 on 2024-10-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_me', '0002_remove_question_content_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertechnologyprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
