# Generated by Django 5.1.2 on 2024-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_me', '0003_usertechnologyprogress_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
